bmarlow/whoa.txt
=> First Commit

rvepak/README.md
Edited the readme.md to test the merge
=> Initial commit

bmarlow/fizzbuzz.py, bmarlow/grid_printer.py, bmarlow/whoa.txt
I hope I can look back at grid_printer and laugh at some point.
=> Commiting week two assignments

bmarlow/fizzbuzz.py
Changed the approach to fizzbuzz to use less % operations
=> Updating FizzBuzz

rvepak/gridPrinter.py
Added a new file for GridPrinter.py
=> RV - adding gridPrinter.py

rvepak/fibonacci.py, rvepak/fizzBizz.py, rvepak/gridPrinter.py
1. Added fizzBuzz.py
2. Changed gridPrinter.py to use argparse and also better variable names
=> RV - Added fizzBuzz and changed gridPrinter

rhaegal/series.py
Finishing lab #3 (for the second time)
=> Lab Exercise#3

jhputnam/fizzbuzz.py, jhputnam/grid-printer.py
Wasn't all that happy with the grid printer I banged out in class, so I re-did it. The grid printer I'm checking in is based off part 3 of the grid printer lab, and is fully-functional as far as I know. 
It's not the most elegant thing in the world, but it does work. What was that you were saying about 50 line solutions? :)
Fizzbuzz lab was quite straightforward, although I certainly took the path of least resistance. I'm sure there are optimizations to be had here, but right now I'm not entirely sure what they might be.
=> Checking in full grid printer and fizzbuzz labs.

.idea/vcs.xml, FizzBuzz.EV.2017 01 20.py, GridPrinter.EV.2017 01 18.py, test.ev.2017 01 20.py
=> test and grid printer lab

jingdai/fizzbuzz.py, jingdai/hw1.py, jingdai/newfile.txt, jingdai/printGrid.py, jingdai/secondfile.txt
=> approve the changes to jingdai folder

mmf69/Fizz_Buzz.py, mmf69/Grid_Printer_Excercise.py
=> Week Two Homework

mbozee/Untitled.ipynb, mbozee/seattle-open-data/seattle-real-time-fire-911-calls/seattle-fire-json.py, mbozee/session_2/fizzbuzz.py, mbozee/session_2/grid_printer.py, mbozee/session_2/series.py, mbozee/session_2/think_python_8-12.py, mbozee/session_3/list_lab.py, mbozee/web_scraper/web_scraper.py, mbozee/web_scraper/web_scraper2.py
Ran into trouble with my repo. Had to restore from UWPCE repo. My files added.
Please let me know if I'm making a pull request incorrectly. Thanks!
=> session 2 labs/hw, session 3 lab, seattle open data

rvepak/mailroom.py
=> RV - adding mailroom.py

ejviola/BLSscraper.py, ejviola/mailroom.py
I chose to form this around a while loop so the user could add data, create a report, or send a thank you note while 'remembering' any new records.
=> Mailroom lab.

follej/Lightning_Talk/plot_radar_track.py, follej/session03/mailroom.py
=> Session 3 hw

rvepak/sample.txt, rvepak/sherlock-small.txt, rvepak/trigam_algo.py
=> RV - added trigam algo

gpmora10/Session04/dictmailroom.py
dictmailroom.py in session04 now uses dictionaries rather than lists.
Added individual donation report as well as aggregate donation report.
=> Refactored mailroom.py from Session03

rhaegal/Session4/Dict_Lab.py, rhaegal/Session4/kata14.py
Here is the slightly modified code I was showing in class. It's still not playing nice with quotes and parens
=> Horribly broken attempt at kata14

ejviola/mailroom.py
Will now write a new file if the file doesn't exist or if we get an EOF error (like if there was an error while the file was open as write but never closed correctly)
Will now loop user input to make sure it's a float for donation_amount
Minor refactoring here and there
=> Updated mailroom with some error handling.

raudelb/session03/list_lab.py, raudelb/session03/mailroom.py, raudelb/session03/rot13.py, raudelb/session03/slicing_lab.py
Hi, 
I want to update my homework for  session 03. Thanks.
=> session03 completed

jhputnam/cigar_party.py, jhputnam/mailroom.py, jhputnam/test_cigar_party.py, jhputnam/test_mailroom.py
Cigar party solution was extremely basic, and hasn't changed since the night of class. It works, so I didn't see the need to be fancy with the logic.
Mailroom refactor and testing was pretty brutal and un-fun.
I spent more than 10 hours scratching my head and slogging through what I could, which might seem like a lot, but it's rather normal for my somewhat snail-like pace.
Mailroom helper functions are now mostly generic, and following Rick's in-class suggestion from a while back, I moved all of my user-input to main. I initially tried moving it all under if __name__ == '__main__' similar to Rick's examples, but pylint REALLY doesn't like that because of all the re-definition going on. 
The user input and function calls in main are left out of the test coverage, but my patience and …
=> Adding cigar party and mailroom testing assignment.

rvepak/mail_room_object.py
=> Added mail_room_object based on object orientation

rvepak/converter.py
=> UV - added converter.py

follej/session04/sherlock.txt, follej/session04/sherlock_small.txt, follej/session04/trigram.py, follej/session05/mailroom.py, follej/session06/mailroom.py, follej/session07/ConvertRomanArabic.py, follej/session07/donor.py, follej/session07/initial_donor_list.csv, follej/session07/mailroom_oo.py, follej/session07/test_ConvertRomanArabic.py, follej/session07/test_donor.py
Includes a refactored class mailroom with a new donor class and the Roman numeral to Arabic converter class.
=> Session07 Assignments

raudelb/session05/exceptions_lab.py, raudelb/session05/mainroom_updated.py, raudelb/session08/circle.py, raudelb/session08/circle_test.py
=> Updating assignments 05 08

jhputnam/circle_class.py, jhputnam/test_circle.py
First cut of circle class and testing. Managed to get the add and multiply to actually return a new object with the new value, as shown in the assignment example. Also managed to get multiplication to work both directions.
=> Adding circle class and testing for circle class.

raudelb/session06/args_kwargs_lab.py
Session06 Lab is completed, please, any suggestion I appreciate it. Thanks.
=> session06 Lab completed
